---
title: "Weinberg Lab manual"
output: 
  github_document:
    toc: true
---

Welcome! This manual describes the principles and practices we use for managing projects. 

# Getting Started

For working with data (cleaing, analysis etc.) we primarily use R and Stata. We also use Python occasionally. 

We use Git + Github for version control and Github for task management. 

Below are some resources to get you started. 

## Project Management

- [Good enough practices in scientific computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
- [Code and Data for the Social Sciences: A Practitioner’s Guide](https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf)

## R

- [R for Data Science](http://r4ds.had.co.nz/) - this book will introduce you to R through the *tidyverse* suite of packages and introduce project management in with R/RStudio. The online version is free and you can [order a physical copy on Amazon](https://www.amazon.com/R-Data-Science-Hadley-Wickham/dp/1491910399/).

## Stata

- [UNC tutorial](http://www.cpc.unc.edu/research/tools/data_analysis/statatutorial)

## Python

- asdfk

## Git

RStudio has a simple 

- [Software Carpenty](http://swcarpentry.github.io/git-novice/)
